<?php

 function buildModal($contact) {
        $elementId = 'update-contact';
        echo '<div id="'.$elementId.'" tabindex="-1">';
        echo    '<div class="modal-dialog">';
        echo        '<div class="modal-content">';
        echo            '<div class="modal-header">';
        echo                '<a class="close" style="color:white;" href="ContactPage.php">&times; </a>';
        echo                '<h4 class="modal-title" id="'.$elementId.'-label">'.$contact->getFullName().'</h4>';
        echo            '</div>';
        echo            '<div id="'.$elementId.'-modal-body" class="modal-body" style="max-height: 65vh;">';
        echo                '<form class="form-horizontal">';
        echo                    '<div class="form-group">';
        echo                        '<label for="'.$elementId.'-first-name" class="col-sm-3 control-label">First Name</label>';
        echo                        '<div class="col-sm-9">';
        echo                            '<input type="text" class="form-control" id="'.$elementId.'-first-name" placeholder="First Name" value="'.$contact->getFirstName().'" required/>';
        echo                        '</div>';
        echo                    '</div>';
        echo                    '<div class="form-group">';
        echo                        '<label for="'.$elementId.'-last-name" class="col-sm-3 control-label">Last Name</label>';
        echo                        '<div class="col-sm-9">';
        echo                            '<input type="text" class="form-control" id="'.$elementId.'-last-name" placeholder="Last Name" value="'.$contact->getLastName().'"/>';
        echo                        '</div>';
        echo                    '</div>';
        echo                    '<div class="form-group">';
        echo                        '<label for="'.$elementId.'-company" class="col-sm-3 control-label">Company</label>';
        echo                        '<div class="col-sm-9">';
        echo                            '<input type="text" class="form-control" id="'.$elementId.'-company" placeholder="Company"  value="'.$contact->getCompany().'"/>';
        echo                        '</div>';
        echo                    '</div>';
        echo                    '<div class="form-group">';
        echo                        '<label for="'.$elementId.'-phone" class="col-sm-3 control-label">Phone Number</label>';
        echo                        '<div class="col-sm-9">';
        echo                            '<input type="tel" class="form-control" id="'.$elementId.'-phone" placeholder="Phone Number" value="'.$contact->getPhone().'"/>';
        echo                        '</div>';
        echo                    '</div>';
        echo                    '<div class="form-group">';
        echo                        '<label for="'.$elementId.'-email" class="col-sm-3 control-label">Email</label>';
        echo                        '<div class="col-sm-9">';
        echo                            '<input type="email" class="form-control" id="'.$elementId.'-email" placeholder="Email"  value="'.$contact->getEmail().'"/>';
        echo                        '</div>';
        echo                    '</div>';
        echo                    '<div class="form-group">';
        echo                        '<label for="'.$elementId.'-url" class="col-sm-3 control-label">URL</label>';
        echo                        '<div class="col-sm-9">';
        echo                            '<input type="url" class="form-control" id="'.$elementId.'-url" placeholder="Url"  value="'.$contact->getUrl().'"/>';
        echo                        '</div>';
        echo                    '</div>';
        echo                    '<div class="form-group">';
        echo                        '<label for="'.$elementId.'-birthday" class="col-sm-3 control-label">Birthday</label>';
        echo                        '<div class="col-sm-9">';
        echo                           '<input type="date" class="form-control" id="'.$elementId.'-birthday"  value="'.$contact->getBirthday().'"/>';
        echo                        '</div>';
        echo                    '</div>';
        echo                    '<div class="form-group">';
        echo                        '<label for="'.$elementId.'-date" class="col-sm-3 control-label">Date</label>';
        echo                        '<div class="col-sm-9">';
        echo                            '<input type="date" class="form-control" id="'.$elementId.'-date"  value="'.$contact->getDate().'"/>';
        echo                        '</div>';
        echo                    '</div>';
        echo                    '<div class="form-group">';
        echo                        '<label for="'.$elementId.'-buidling-number" class="col-sm-3 control-label">Building #</label>';
        echo                        '<div class="col-sm-9">';
        echo                            '<input type="text" class="form-control" id="'.$elementId.'-building-number" placeholder="House or Building Number" value="'.$contact->getAddress()->getBuildingNumber().'"/>';
        echo                        '</div>';
        echo                    '</div>';
        echo                    '<div class="form-group">';
        echo                        '<label for="'.$elementId.'-street-name" class="col-sm-3 control-label">Street Name</label>';
        echo                        '<div class="col-sm-9">';
        echo                            '<input type="text" class="form-control" id="'.$elementId.'-street-name" placeholder="Street Name" value="'.$contact->getAddress()->getStreetName().'"/>';
        echo                        '</div>';
        echo                    '</div>';
        echo                    '<div class="form-group">';
        echo                        '<label for="'.$elementId.'-town-name" class="col-sm-3 control-label">Town/City</label>';
        echo                        '<div class="col-sm-9">';
        echo                            '<input type="text" class="form-control" id="'.$elementId.'-town-name" placeholder="Town/City"  value="'.$contact->getAddress()->getTownName().'"/>';
        echo                        '</div>';
        echo                    '</div>';
        echo                    '<div class="form-group">';
        echo                        '<label for="'.$elementId.'-region" class="col-sm-3 control-label">Region</label>';
        echo                        '<div class="col-sm-9">';
        echo                            '<input type="text" class="form-control" id="'.$elementId.'-region" placeholder="Region or Province"  value="'.$contact->getAddress()->getRegion().'"/>';
        echo                        '</div>';
        echo                    '</div>';
        echo                    '<div class="form-group">';
        echo                        '<label for="'.$elementId.'-country" class="col-sm-3 control-label">Country</label>';
        echo                        '<div class="col-sm-9">';
        echo                            '<input type="text" class="form-control" id="'.$elementId.'-country" placeholder="Country"  value="'.$contact->getAddress()->getCountry().'"/>';
        echo                        '</div>';
        echo                    '</div>';
        echo                    '<div class="form-group">';
        echo                        '<label for="'.$elementId.'-post-code" class="col-sm-3 control-label">Post Code</label>';
        echo                        '<div class="col-sm-9">';
        echo                            '<input type="text" class="form-control" id="'.$elementId.'-post-code" placeholder="Postal Code"  value="'.$contact->getAddress()->getPostCode().'"/>';
        echo                        '</div>';
        echo                    '</div>';
        echo                    '<div class="form-group" style="padding-left:30px; padding-right:20px;">';
        echo                        '<label for="'.$elementId.'-notes" class="control-label">Notes</label>';
        echo                        '<textarea id="'.$elementId.'-notes" class="form-control" rows="3"></textarea>';
        echo                    '</div>';                                
        echo                '</form>';
        echo            '</div>';
        echo            '<div class="modal-footer">';
        echo                '<a class="btn btn-primary" href="ContactPage.php">Close</a>';
        echo                '<button type="button" class="btn btn-success" onClick="updateContact()">Save changes</button>';
        echo            '</div>';
        echo        '</div>';
        echo    '</div>';
        echo '</div>';
        
    }

